<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateLoanApplicationsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('loan_applications', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('IDNo');
            $table->string('Loanno')->unique();//autogenerated based on loantype and Memberno
            $table->string('Loancode');//loantypecode
            $table->float('AmountApplied');
            $table->dateTime('ApplicationDate');
            $table->dateTime('EffectDate')->nullable();
            $table->integer('RecoverInterestFirst')->default(0);
            $table->string('IntRate');//interestRate
            $table->string('Rperiod');//repaymentPeriod
            $table->string('Createdby'); 
            $table->string('Approved')->default(0); 
            $table->float('ApprovedAmount')->default(0); 
            $table->float('RepayAmount')->nullable(); 
            $table->integer('IsDisbursed')->default(0); 
            $table->string('ApprovedBy')->nullable(); 
            $table->string('Modifiedby')->nullable();            
            $table->datetime('ApprovedOn')->nullable();
            $table->datetime('ModifiedOn')->nullable();           

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('loan_applications');
    }
}
